config/routes.rb
Rails.application.routes.draw do
  root "posts#index", as: 'home'
  # resources :posts
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many:comments
    validates:title,presence:true,length:{minimum:3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post=Post.find(params[:post_id])
        @comment=@post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post= Post.find(params[:post_id])
        @comment= @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end 

    private def comment_params
        params.require(:comment).permit(:username,:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "jinu", password:"1234",except:[:index,:show]
    def index
        @posts = Post.all
    end
    def show
        @post =Post.find(params[:id])
    end

    def new
        @post=Post.new
    end
    def create
        #   render plain:params[:post].inspect
        # @post=Post.new(params[:post])
        @post=Post.new(post_params)
        
        if(@post.save)
            redirect_to @post
        else 
            render 'new'
        end
    end

    def update
        @post=Post.find(params[:id])
        
        if(@post.update(post_params))
            redirect_to @post
        else 
            render 'edit'
        end
    end

    def edit
        @post=Post.find(params[:id])
    end

    def destroy
        @post= Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end 

    private def post_params
        params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<br>
<hr>
<h2>Comments</h2>
<% @post.comments.each do |comment| %>

<div class="blog">
<div class="img">
<div class="in">
<span class="name"><b><%= comment.username %></b></span>
<span class="bd"><p><%= comment.body %></p></span>
<span><%= link_to "Delete",[comment.post,comment],method: :delete,data:{confirm:"Are You want to delete this post?"},class:'dell' %>
</span></div>

</div>
</div>
<% end %>

app/views/comments/_form.html.erb
<hr>
<h2>Post Comment</h2>
<%= form_for ([@post,@post.comments.build]) do |f|  %>
    <% if @post.errors.any? %>
        <%  @post.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
    <%end %>
    <%end %>
    <b><%= f.label :username %><b><br/>
    <%= f.text_field :username ,class:'inp'%>
   <br>
    <br><%= f.label :body %></br>
    <%= f.text_area :body %>
  

    <p>
    <%= f.submit :'Post Comment',class:'post' %><br/>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="nav">
   
   <p><%= link_to "Create New",new_post_path,class:'link'  %></p>
   <p><%= link_to "Home",home_path ,class:'link' %></p>
   </div>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="postblock">
<div class="newblog">
<h2>Edit Post</h2>
<%= form_for :post,url:post_path(@post),method: :patch do |f|  %>
    

    <%= f.label :title %><br/>
    <%= f.text_field :title ,class:'inp' %><br>
    <%= f.label :body %><br/>
    <%= f.text_area :body ,class:'inpp' %><br>
    <%= f.submit :'Update Post' ,class:'post up' %>
<% end %>
<div>
</div>

app/views/posts/index.html.erb
<div class="container">

<div class="col1"></div>
<div class="col2">
<h1>All Posts</h1>
<% @posts.each do |post| %>
 
 <div class="blog">
<div class="img">
<div class="pr"></div>
<div class="in">
<span class="name"><%= post.title %></span>
<span class="bd"><%= post.body %></span>
<%= link_to "Read More",post_path(post) ,class:'post' %>
</div>

</div>
</div>
<% end %>
</div>
<div class="col3"></div>
</div>

app/views/posts/new.html.erb
<div class="postblock">
<div class="newblog">
<h2>Create Post</h2>
<%= form_for :post,url:posts_path do |f|  %>
  
    <%= f.label :title %><br/>
    <%= f.text_field :title ,class:'inp' %><br>
    <%= f.label :body %><br/>
    <%= f.text_area :body ,class:'inpp' %><br>
    <%= f.submit :'Save Post' ,class:'post up' %>
<% end %>
<div>
</div> 

app/views/posts/show.html.erb
<div class="postblock">
<div class="newblog">
<h1>Posted By :<%= @post.title %></h1>
<p> <%= @post.body %> </p>
<%= link_to "Edit",edit_post_path(@post) ,class:'post' %>
<%= link_to "Delete",post_path(@post),method: :delete,data:{confirm:"Are You want to delete this post?"},class:'del' %><br>
<div>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>

</div>